import { GetSqlStatementResponse } from "../../types";

export function getSqlStatementResponse(id: string): GetSqlStatementResponse {
  return {
    jsonrpc: "2.0",
    id: 1,
    error: null,
    result: {
      sqlStatement: {
        id: id,
        statementHash: "9d9d5d462b0e4aaf18d17283b1ea2ff9bb30a285c0fe066754fed18f34f80388",
        sql: "SELECT * FROM ethereum.core.fact_transactions LIMIT 100000",
        columnMetadata: {
          types: [
            "fixed",
            "timestamp_ntz",
            "text",
            "text",
            "real",
            "fixed",
            "text",
            "text",
            "text",
            "real",
            "real",
            "real",
            "fixed",
            "real",
            "real",
            "text",
            "text",
            "object",
          ],
          columns: [
            "BLOCK_NUMBER",
            "BLOCK_TIMESTAMP",
            "BLOCK_HASH",
            "TX_HASH",
            "NONCE",
            "POSITION",
            "ORIGIN_FUNCTION_SIGNATURE",
            "FROM_ADDRESS",
            "TO_ADDRESS",
            "ETH_VALUE",
            "TX_FEE",
            "GAS_PRICE",
            "GAS_LIMIT",
            "GAS_USED",
            "CUMULATIVE_GAS_USED",
            "INPUT_DATA",
            "STATUS",
            "TX_JSON",
          ],
          colTypeMap: {
            NONCE: "real",
            STATUS: "text",
            TX_FEE: "real",
            TX_HASH: "text",
            TX_JSON: "object",
            GAS_USED: "real",
            POSITION: "fixed",
            ETH_VALUE: "real",
            GAS_LIMIT: "fixed",
            GAS_PRICE: "real",
            BLOCK_HASH: "text",
            INPUT_DATA: "text",
            TO_ADDRESS: "text",
            BLOCK_NUMBER: "fixed",
            FROM_ADDRESS: "text",
            BLOCK_TIMESTAMP: "timestamp_ntz",
            CUMULATIVE_GAS_USED: "real",
            ORIGIN_FUNCTION_SIGNATURE: "text",
          },
        },
        userId: "clf8qd1eb0000jv08kbuw0dy4",
        tags: {
          sdk_package: "python",
          sdk_version: "1.0.2",
          sdk_language: "python",
        },
        createdAt: "2023-04-05T18:53:59.000Z",
        updatedAt: "2023-04-05T18:53:59.000Z",
      },
    },
  };
}
